version: 2.1
orbs:
  node: circleci/node@4.7
  
jobs:
  build:
    version: '16.10'
    pkg-manager: npm
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - run: npm install
      - run: npm test
      - run: npm build
