version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/RizwanMushtaq/angular-weather-app/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm ci
          cd ./node_modules/protractor && npm i webdrivermanager@latest
          npm run test
          npm run build
          

workflows:
  my-custom-workflow:
    jobs:
      - build
